/**:
  ros__parameters:
    serial_name: "/dev/ttyCLAP"
    parse_type: "BINARY"
    baud_rate: 460800
    activate_ntrip: "true" #Runs ntrip_client_ros package

    # Topics
    clap_imu_data: "clap/clap_msgs/clap_imu"
    clap_ins_data: "clap/clap_msgs/clap_ins"
    imu_topic: "clap/ros/imu"
    nav_sat_fix_topic: "clap/ros/gps_nav_sat_fix"
    autoware_orientation_topic: "clap/autoware_orientation"
    twist_topic: "clap/ros/twist_with_covariance_stamped"
    odom_topic: "clap/ros/odom"
    raw_nav_sat_fix_topic: "clap/ros/raw_nav_sat_fix"
    raw_imu_topic: "clap/ros/raw_imu"

    #Package name of NTRIP Client ROS
    ntrip_client_package_name: "ntrip_client_ros"
    #Subscribe to mavros_msgs/RTCM topic
    rtcm_topic: "/sensing/gnss/ntrip/rtcm"

    ### Time System Selection 
    #   0 --> GPS Global Time 
    #   1 --> ROS Rclcpp System time     
    time_system_selection: 0

    ### ENU -> NED Transform Selection
    enu_ned_transform: "true"

    #Frame values
    gnss_frame: "GNSS_INS/gnss_ins_link"
    imu_frame: "GNSS_INS/gnss_ins_link"
    autoware_orientation_frame: "GNSS_INS/gnss_ins_link"
    twist_frame: "GNSS_INS/gnss_ins_link"

    debug: "true"