/**:
  ros__parameters:
    serial_name: "/dev/ttyCLAP"
    parse_type: "BINARY"
    baud_rate: 460800
    activate_ntrip: "true"
    ntrip_ip: "212.156.70.42"
    ntrip_user_name: "K0734151301"
    ntrip_password: "GzMSQg"
    ntrip_mount_point: "VRSRTCM31"
    ntrip_port: 2101
    ntrip_lat: 41.018893949 
    ntrip_lon: 28.890924848
    # Topics
    clap_imu_data: "clap_imu"
    clap_ins_data: "clap_ins"
    imu_topic: "gnss/imu"
    nav_sat_fix_topic: "gnss/gps"
    autoware_orientation_topic: "gnss/autoware_orientation"
    twist_topic: "gnss/twist"
    odom_topic: "gnss/odom"
    ### Time System Selection 
    #   0 --> GPS Global Time 
    #   1 --> ROS Rclcpp System time     
    time_system_selection: 0

    ### ENU -> NED Transform Selection
    enu_ned_transform: "false"

    #Frame values
    gnss_frame: "gnss_ins_link"
    imu_frame: "gnss_ins_link"
    autoware_orientation_frame: "gnss_ins_link"
    twist_frame: "gnss_ins_link"

    debug: "true"