# Standart Deviations

ENU baseline_std             # From the base to rover baseline vector, components standard deviations

float32  sigma_v_x                 # Northing velocity standard deviation
float32  sigma_v_y                 # Easting velocity standard deviation
float32  sigma_v_z                 # velocity standard deviation

float32  sigma_lat                # Latitude standard deviation
float32  sigma_lon                # Longitude standard deviation
float32  sigma_alt                # Height standard deviation

float32  sigma_ecef_x             # ECEF_X standard deviation
float32  sigma_ecef_y             # ECEF_Y standard deviation
float32  sigma_ecef_z             # ECEF_Z standard deviation
